-- MySQL Script generated by MySQL Workbench
-- Sat Jul  1 10:52:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Navigator
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Navigator
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Navigator` DEFAULT CHARACTER SET utf8 ;
USE `Navigator` ;

-- -----------------------------------------------------
-- Table `Navigator`.`Locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Navigator`.`Locations` (
  `id` BIGINT(255) NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Navigator`.`Drivers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Navigator`.`Drivers` (
  `id` BIGINT(255) NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Navigator`.`Transportation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Navigator`.`Transportation` (
  `id` BIGINT(255) NOT NULL,
  `name` VARCHAR(45) NULL,
  `driver_id` BIGINT(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Transportation_Drivers1_idx` (`driver_id` ASC),
  CONSTRAINT `fk_Transportation_Drivers1`
    FOREIGN KEY (`driver_id`)
    REFERENCES `Navigator`.`Drivers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Navigator`.`Routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Navigator`.`Routes` (
  `id` BIGINT(255) NOT NULL,
  `location_a` BIGINT(255) NULL,
  `location_b` BIGINT(255) NULL,
  `duration` INT NULL,
  `transportation_id` BIGINT(255) NOT NULL,
  `cost` INT NULL,
  `distance` INT NULL,
  INDEX `fk_Routes_Transportation1_idx` (`transportation_id` ASC) ,
  INDEX `location_a_idx` (`location_a` ASC) ,
  INDEX `location_b_idx` (`location_b` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Routes_Transportation1`
    FOREIGN KEY (`transportation_id`)
    REFERENCES `Navigator`.`Transportation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `location_a`
    FOREIGN KEY (`location_a`)
    REFERENCES `Navigator`.`Locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `location_b`
    FOREIGN KEY (`location_b`)
    REFERENCES `Navigator`.`Locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Navigator`.`Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Navigator`.`Type` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;